extends SceneTree

const Flight = preload("res://scripts/atmospheric_flight.gd")
const Thermal = preload("res://scripts/thermal_signature.gd")

func _initialize() -> void:
	var released := Flight.drag_heat_j(Vector3(10.0, 0.0, 0.0), Vector3(8.0, 0.0, 0.0), 2.0)
	assert(is_equal_approx(released, 3.6), "drag heat is ten percent of kinetic energy lost")
	assert(Flight.HEAT_FRACTION == 0.1)
	assert(is_equal_approx(released, Flight.drag_heat_j(Vector3(10, 0, 0), Vector3(9, 0, 0), 2.0) + Flight.drag_heat_j(Vector3(9, 0, 0), Vector3(8, 0, 0), 2.0)), "splitting a velocity loss conserves deposited heat")
	assert(Flight.drag_heat_j(Vector3.ZERO, Vector3.ZERO, 2.0) == 0.0)
	assert(Flight.drag_heat_j(Vector3(8.0, 0.0, 0.0), Vector3(10.0, 0.0, 0.0), 2.0) == 0.0, "speed gain adds no heat")
	assert(Flight.drag_heat_j(Vector3(10.0, 0.0, 0.0), Vector3.ZERO, 0.0) == 0.0)
	assert(Flight.drag_heat_j(Vector3(NAN, 0.0, 0.0), Vector3.ZERO, 2.0) == 0.0)
	assert(Flight.drag_heat_j(Vector3(INF, 0.0, 0.0), Vector3.ZERO, 2.0) == 0.0)
	assert(Flight.drag_heat_j(Vector3(1e20, 0.0, 0.0), Vector3.ZERO, 2.0) == 0.0, "overflowing kinetic energy is rejected")
	assert(Flight.drag_heat_j(Vector3(1e10, 0.0, 0.0), Vector3.ZERO, 1e300) == 0.0, "overflowing mass product is rejected")

	var absorbed := Thermal.absorb_heat_j(300.0, Thermal.HEAT_CAPACITY_J_K)
	assert(is_equal_approx(float(absorbed.temperature_k), 301.0) and absorbed.hull_damage == 0.0)
	var overflow := Thermal.absorb_heat_j(699.0, Thermal.HEAT_CAPACITY_J_K + Thermal.DAMAGE_ENERGY_J)
	assert(overflow.temperature_k == 700.0 and is_equal_approx(float(overflow.hull_damage), 1.0), "excess heat damages hull")
	var capped := Thermal.absorb_heat_j(699.0, 1e308)
	assert(capped.temperature_k == 700.0 and is_finite(float(capped.hull_damage)), "huge finite impulse caps temperature without overflow")
	assert(Thermal.absorb_heat_j(700.0, 1e308).temperature_k == 700.0)
	assert(Thermal.absorb_heat_j(400.0, 0.0).temperature_k == 400.0)
	assert(Thermal.absorb_heat_j(299.0, 100.0).temperature_k == 299.0 and Thermal.absorb_heat_j(299.0, 100.0).hull_damage == 0.0)
	assert(Thermal.absorb_heat_j(NAN, 100.0).hull_damage == 0.0)
	assert(Thermal.absorb_heat_j(400.0, -1.0).temperature_k == 400.0)
	assert(Thermal.absorb_heat_j(400.0, INF).hull_damage == 0.0)

	var impulse := Thermal.absorb_heat_j(300.0, Thermal.HEAT_CAPACITY_J_K)
	var cooled_step := Thermal.step_temperature(300.0, 0.0, Thermal.HEAT_CAPACITY_J_K, 1.0)
	assert(is_equal_approx(float(impulse.temperature_k), cooled_step), "impulse adds stored heat; step retains separate per-second cooling")
	assert(Thermal.step_temperature(699.99, 0.0, 2e9, 1.0) == 700.0)
	assert(Thermal.overflow_damage(699.99, 0.0, 2e9, 1.0) > 0.0, "continuous overflow damage remains separate")
	assert(Thermal.HEAT_CAPACITY_J_K == 2500000.0 and Thermal.DAMAGE_ENERGY_J == 25000000.0)
	print("AERODYNAMIC_HEAT_OK: energy loss fraction, input guards, storage cap and overflow")
	quit()
