extends SceneTree

func _initialize() -> void: _run.call_deferred()

func _run() -> void:
	var state := GameState.new()
	var initial := state.market_stock("ore", 0)
	var rate := ceili(initial * 0.1)
	assert(state.market_daily_flow("ore") == 0 and state.market_stocks.is_empty())
	assert(state.market_daily_flow("unknown") == 0 and state.market_daily_flow("ore", -2) == 0)
	assert(state.market_transfer("ore", 0, initial, true).is_empty())
	assert(state.market_daily_flow("ORE") == rate)
	var snapshot := state._save_data().duplicate(true)
	state.price("ore")
	state.market_total("ore", 0, 1, true)
	state.market_daily_flow("ore")
	assert(state._save_data() == snapshot, "quotes never advance market simulation")
	var fixed_base_price := state.price_at("ore", 0, 0)
	state.advance_time(GameState.DAY_SECONDS - 1)
	assert(state.market_stock("ore") == 0, "settle at day boundary only")
	var path := "user://market-flow-%d.json" % OS.get_process_id()
	assert(state.save(path).is_empty())
	var resumed := GameState.new()
	assert(resumed.load_save(path).is_empty() and resumed.market_stock("ore") == 0, "loading does not restock")
	resumed.advance_time(1)
	assert(resumed.market_stock("ore") == rate and resumed.price_at("ore", 0, 0) < fixed_base_price)
	state.advance_time(1)
	assert(state.market_stocks == resumed.market_stocks, "saved fractional day resumes exactly")
	var distant := state.market_stock("medicine", 999999999)
	assert(state.market_transfer("medicine", 999999999, GameState.MARKET_CAPACITY - distant, false).is_empty())
	var consumption := -state.market_daily_flow("medicine", 999999999)
	assert(consumption > 0)
	state.advance_time(GameState.DAY_SECONDS)
	assert(state.market_stock("medicine", 999999999) == GameState.MARKET_CAPACITY - consumption, "demand frees a full remote market")
	var separate := GameState.new()
	assert(separate.market_stocks.is_empty() and separate.market_stock("ore") == initial, "separate world economy unaffected")
	var batched := GameState.new()
	assert(batched.load_data(state._save_data()).is_empty())
	batched.advance_time(GameState.DAY_SECONDS * 3)
	for i in range(3): state.advance_time(GameState.DAY_SECONDS)
	assert(batched.market_stocks == state.market_stocks, "batched and split days match")
	var balanced := GameState.new()
	assert(balanced.market_transfer("ore", 0, 1, true).is_empty())
	assert(balanced.market_transfer("food", 0, 1, false).is_empty())
	assert(balanced.market_daily_flow("ore") == 1 and balanced.market_daily_flow("food") == -1)
	assert(balanced.jump(17).is_empty())
	assert(balanced.market_stocks.is_empty(), "jump settlement clamps at baseline and prunes settled records")
	assert(FileAccess.file_exists(path))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	if DisplayServer.get_name() != "headless":
		var game = load("res://scenes/main.tscn").instantiate()
		root.add_child(game)
		await process_frame
		game.set_process(false)
		game.set_physics_process(false)
		game.state.market_transfer("ore", 0, game.state.market_stock("ore"), true)
		game.state.market_transfer("food", 0, 80, false)
		game.open_menu("market")
		await RenderingServer.frame_post_draw
		root.get_texture().get_image().save_png("user://market-flow.png")
		game.session.leave()
		game.sound.shutdown()
		game.queue_free()
		await process_frame
		await process_frame
	print("MARKET_FLOW_OK: bounded supply/demand, quotes, persistence, split time, remote markets, isolation and sparse recovery")
	quit()
